import type { FoodItem } from "@workspace/api-client-react";

export const DEMO_SHORTS = [
  { id: 1, title: "Perfect Butter Chicken at Home", description: "A quick recipe for a rich, creamy curry.", authorName: "Foodie Kitchen", authorRole: "creator", thumbnailUrl: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=700&q=85", videoUrl: "https://samplelib.com/preview/mp4/sample-5s.mp4", views: 1240, likes: 86 },
  { id: 2, title: "Crispy Paneer Tikka in Minutes", description: "Make restaurant-style paneer at home.", authorName: "Spice Stories", authorRole: "creator", thumbnailUrl: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=700&q=85", videoUrl: "https://samplelib.com/preview/mp4/sample-10s.mp4", views: 980, likes: 64 },
  { id: 3, title: "Street Style Hakka Noodles", description: "Wok-tossed noodles with bold flavors.", authorName: "Wok This Way", authorRole: "creator", thumbnailUrl: "https://images.unsplash.com/photo-1552611052-33e04de081de?w=700&q=85", videoUrl: "https://samplelib.com/preview/mp4/sample-15s.mp4", views: 1560, likes: 112 },
  { id: 4, title: "Easy Homemade Biryani", description: "Simple steps for fragrant homemade biryani.", authorName: "The Curry Club", authorRole: "creator", thumbnailUrl: "https://images.unsplash.com/photo-1563379091339-03246963d96c?w=700&q=85", videoUrl: "https://samplelib.com/preview/mp4/sample-20s.mp4", views: 2100, likes: 147 },
];

const NEW_DISH_IMAGES: Record<string, string> = {
  "Aloo Gobi": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9b/Aloo_Gobi_Sabzi.jpg/960px-Aloo_Gobi_Sabzi.jpg",
  "Vegetable Korma": "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=900&q=85",
  "Rajma Masala": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/37/Rajma_Masala_%2832081557778%29.jpg/960px-Rajma_Masala_%2832081557778%29.jpg",
  "Malai Kofta": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/40/Malai_Kofta_Curry.jpg/960px-Malai_Kofta_Curry.jpg",
  "Baingan Bharta": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4d/Baigan_Bharta_from_Nagpur.JPG/960px-Baigan_Bharta_from_Nagpur.JPG",
  "Matar Paneer": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=900&q=85",
  "Chicken Tikka": "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=900&q=85",
  "Lamb Kebab": "https://images.unsplash.com/photo-1544025162-d76694265947?w=900&q=85",
  "Fish Curry": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4f/Meen_curry_%28fish_curry%29_from_Kerala%2C_traditionally_prepared_in_earthern_pot.jpg/960px-Meen_curry_%28fish_curry%29_from_Kerala%2C_traditionally_prepared_in_earthern_pot.jpg",
  "Chicken Korma": "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=900&q=85",
  "Prawn Masala": "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=900&q=85",
  "Chicken Seekh Kebab": "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=900&q=85",
  "Hot and Sour Soup": "https://loremflickr.com/900/700/hot-and-sour-soup?lock=201",
  "Spring Rolls": "https://loremflickr.com/900/700/spring-rolls?lock=101",
  "Manchow Soup": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Chicken_Manchow_Soup.jpg/960px-Chicken_Manchow_Soup.jpg",
  "Szechuan Chicken": "https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=900&q=85",
  "Honey Chilli Potato": "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=900&q=85",
  "Garlic Noodles": "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=900&q=85",
  "Vegetable Spring Rice": "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=900&q=85",
  "Kung Pao Tofu": "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=900&q=85",
  "Four Cheese Pizza": "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=900&q=85",
  "Spaghetti Carbonara": "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=900&q=85",
  "Lasagna": "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=900&q=85",
  "Mushroom Risotto": "https://loremflickr.com/900/700/mushroom-risotto?lock=102",
  "Pesto Pasta": "https://images.unsplash.com/photo-1556761223-4c4282c73f77?w=900&q=85",
  "Garlic Bread": "https://images.unsplash.com/photo-1573140401552-3fab0b24306f?w=900&q=85",
  "Bruschetta": "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=900&q=85",
  "Chicken Wings": "https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=900&q=85",
  "Chicken Wrap": "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=900&q=85",
  "Hot Dog": "https://loremflickr.com/900/700/hot-dog?lock=303",
  "Cheese Nachos": "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=900&q=85",
  "Fish and Chips": "https://images.unsplash.com/photo-1579208030886-b937da0925dc?w=900&q=85",
  "Chicken Nuggets": "https://images.unsplash.com/photo-1562967916-eb82221dfb92?w=900&q=85",
  "Veggie Tacos": "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=900&q=85",
  "Jalapeno Poppers": "https://upload.wikimedia.org/wikipedia/commons/e/eb/Jalapeno_poppers.png",
  "Kheer": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7f/Kheer_Rice_Pudding_Indian_Sweet_Buffalo_New_York.jpg/960px-Kheer_Rice_Pudding_Indian_Sweet_Buffalo_New_York.jpg",
  "Jalebi": "/jalebi.png",
  "Kulfi": "https://images.unsplash.com/photo-1579954115545-a95591f28bfc?w=900&q=85",
  "Gajar Halwa": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/96/Delicious_Gajar_Ka_Halwa.jpg/960px-Delicious_Gajar_Ka_Halwa.jpg",
  "Rasmalai": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/10/Rasmalai_3.jpg/960px-Rasmalai_3.jpg",
  "Rasgulla": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/10/Rasmalai_3.jpg/960px-Rasmalai_3.jpg",
  "Mango Cheesecake": "https://images.unsplash.com/photo-1549903072-7e6e0bedb7fb?w=900&q=85",
  "Ice Cream Sundae": "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=900&q=85",
  "Cold Coffee": "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=900&q=85",
  "Fresh Lime Soda": "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=900&q=85",
  "Watermelon Juice": "https://images.unsplash.com/photo-1523677011781-c91d1bbe2f9e?w=900&q=85",
  "Iced Tea": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=900&q=85",
  "Coconut Water": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5b/Coconut_water_at_restaurant_in_Ko_Samui.jpg/960px-Coconut_water_at_restaurant_in_Ko_Samui.jpg",
  "Blueberry Smoothie": "https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=900&q=85",
  "Virgin Mojito": "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=900&q=85",
};

export const DEMO_FOOD_ITEMS: FoodItem[] = [
  {
    id: 1,
    name: "Butter Chicken",
    description: "Creamy tomato-based curry with tender chicken pieces. A North Indian classic.",
    price: 14.99,
    imageUrl: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fb/Butter_Chicken%2C_City_Grill_Kottayam.jpg/960px-Butter_Chicken%2C_City_Grill_Kottayam.jpg",
    category: "Non-Veg",
    cafeId: 1,
    cafeName: "Spice Garden Cafe",
    available: true,
    rating: 4.8,
    reviewCount: 120,
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    name: "Paneer Tikka Masala",
    description: "Grilled cottage cheese in a spiced tomato-cream gravy. Rich and aromatic.",
    price: 12.99,
    imageUrl: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/64/Paneer_Tikka_Masala_%282026%29_01.jpg/960px-Paneer_Tikka_Masala_%282026%29_01.jpg",
    category: "Veg",
    cafeId: 1,
    cafeName: "Spice Garden Cafe",
    available: true,
    rating: 4.7,
    reviewCount: 98,
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    name: "Hakka Noodles",
    description: "Wok-tossed noodles with crisp veggies and savory sauces.",
    price: 9.99,
    imageUrl: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=900&q=85",
    category: "Chinese",
    cafeId: 1,
    cafeName: "Spice Garden Cafe",
    available: true,
    rating: 4.5,
    reviewCount: 75,
    createdAt: new Date().toISOString(),
  },
  {
    id: 4,
    name: "Kung Pao Chicken",
    description: "Spicy stir-fried chicken with peanuts, chili, and Sichuan pepper.",
    price: 15.99,
    imageUrl: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=900&q=85",
    category: "Chinese",
    cafeId: 2,
    cafeName: "Golden Wok",
    available: true,
    rating: 4.9,
    reviewCount: 210,
    createdAt: new Date().toISOString(),
  },
  {
    id: 5,
    name: "Dim Sum Basket",
    description: "Six assorted steamed dumplings with prawn, pork, and vegetable varieties.",
    price: 11.99,
    imageUrl: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=900&q=85",
    category: "Chinese",
    cafeId: 2,
    cafeName: "Golden Wok",
    available: true,
    rating: 4.6,
    reviewCount: 87,
    createdAt: new Date().toISOString(),
  },
  {
    id: 6,
    name: "Veg Manchurian",
    description: "Crispy vegetable balls in a tangy, spicy Manchurian sauce.",
    price: 8.99,
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?w=900&q=85",
    category: "Chinese",
    cafeId: 2,
    cafeName: "Golden Wok",
    available: true,
    rating: 4.4,
    reviewCount: 63,
    createdAt: new Date().toISOString(),
  },
  {
    id: 7,
    name: "Dal Makhani",
    description: "Slow-cooked black lentils simmered overnight with butter and cream.",
    price: 10.99,
    imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=900&q=85",
    category: "Veg",
    cafeId: 1,
    cafeName: "Spice Garden Cafe",
    available: true,
    rating: 4.6,
    reviewCount: 88,
    createdAt: new Date().toISOString(),
  },
  {
    id: 8,
    name: "Chicken Biryani",
    description: "Fragrant basmati rice layered with spiced chicken, saffron, and onions.",
    price: 16.99,
    imageUrl: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5b/Chicken_biriyani-_My_cafe_restaurant_-_Meghalaya_DSC_009.jpg/960px-Chicken_biriyani-_My_cafe_restaurant_-_Meghalaya_DSC_009.jpg",
    category: "Non-Veg",
    cafeId: 1,
    cafeName: "Spice Garden Cafe",
    available: true,
    rating: 4.9,
    reviewCount: 304,
    createdAt: new Date().toISOString(),
  },
  {
    id: 9,
    name: "Margherita Pizza",
    description: "Wood-fired pizza with tomato, fresh mozzarella, basil, and olive oil.",
    price: 13.99,
    imageUrl: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=900&q=85",
    category: "Italian",
    cafeId: 1,
    cafeName: "Spice Garden Cafe",
    available: true,
    rating: 4.7,
    reviewCount: 114,
    createdAt: new Date().toISOString(),
  },
  {
    id: 10,
    name: "Classic Chicken Burger",
    description: "Crispy chicken fillet with lettuce, tomato, and house sauce in a toasted bun.",
    price: 10.99,
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=900&q=85",
    category: "Fast Food",
    cafeId: 2,
    cafeName: "Golden Wok",
    available: true,
    rating: 4.6,
    reviewCount: 92,
    createdAt: new Date().toISOString(),
  },
  {
    id: 11,
    name: "Gulab Jamun",
    description: "Soft milk-solid dumplings soaked in fragrant cardamom sugar syrup.",
    price: 5.99,
    imageUrl: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=900&q=85",
    category: "Desserts",
    cafeId: 1,
    cafeName: "Spice Garden Cafe",
    available: true,
    rating: 4.8,
    reviewCount: 76,
    createdAt: new Date().toISOString(),
  },
  {
    id: 12,
    name: "Mango Lassi",
    description: "Refreshing creamy yogurt drink blended with ripe Alphonso mangoes.",
    price: 4.99,
    imageUrl: "https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=900&q=85",
    category: "Beverages",
    cafeId: 1,
    cafeName: "Spice Garden Cafe",
    available: true,
    rating: 4.7,
    reviewCount: 64,
    createdAt: new Date().toISOString(),
  },
  {
    id: 13, name: "Palak Paneer", description: "Tender paneer in a silky spinach gravy with gentle spices.", price: 11.99,
    imageUrl: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a2/Palak_Paneer_curry_on_plate.jpg/960px-Palak_Paneer_curry_on_plate.jpg", category: "Veg", cafeId: 1, cafeName: "Spice Garden Cafe",
    available: true, rating: 4.6, reviewCount: 71, createdAt: new Date().toISOString(),
  },
  {
    id: 14, name: "Chole Bhature", description: "Spiced chickpeas served with fluffy fried bhatura bread.", price: 10.49,
    imageUrl: "https://images.unsplash.com/photo-1626132647523-66f5bf380027?w=900&q=85", category: "Veg", cafeId: 1, cafeName: "Spice Garden Cafe",
    available: true, rating: 4.7, reviewCount: 84, createdAt: new Date().toISOString(),
  },
  {
    id: 15, name: "Tandoori Chicken", description: "Juicy chicken marinated in yogurt and roasted with smoky spices.", price: 15.49,
    imageUrl: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=900&q=85", category: "Non-Veg", cafeId: 1, cafeName: "Spice Garden Cafe",
    available: true, rating: 4.8, reviewCount: 103, createdAt: new Date().toISOString(),
  },
  {
    id: 16, name: "Mutton Rogan Josh", description: "Slow-braised tender mutton in a fragrant Kashmiri gravy.", price: 18.99,
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=900&q=85", category: "Non-Veg", cafeId: 1, cafeName: "Spice Garden Cafe",
    available: true, rating: 4.7, reviewCount: 66, createdAt: new Date().toISOString(),
  },
  {
    id: 17, name: "Schezwan Fried Rice", description: "Wok-tossed rice with vegetables and bold Schezwan chili sauce.", price: 10.99,
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=900&q=85", category: "Chinese", cafeId: 2, cafeName: "Golden Wok",
    available: true, rating: 4.5, reviewCount: 79, createdAt: new Date().toISOString(),
  },
  {
    id: 18, name: "Chilli Paneer", description: "Crispy paneer tossed with peppers, onions, and spicy Indo-Chinese sauce.", price: 11.49,
    imageUrl: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/96/A_full_plate_chilli_paneer_in_Kolkata%2C_West_Bengal.jpg/960px-A_full_plate_chilli_paneer_in_Kolkata%2C_West_Bengal.jpg", category: "Chinese", cafeId: 2, cafeName: "Golden Wok",
    available: true, rating: 4.6, reviewCount: 91, createdAt: new Date().toISOString(),
  },
  {
    id: 19, name: "Penne Arrabbiata", description: "Penne pasta in a spicy tomato, garlic, and basil sauce.", price: 12.49,
    imageUrl: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=900&q=85", category: "Italian", cafeId: 1, cafeName: "Spice Garden Cafe",
    available: true, rating: 4.5, reviewCount: 58, createdAt: new Date().toISOString(),
  },
  {
    id: 20, name: "Creamy Alfredo Pasta", description: "Silky fettuccine tossed in parmesan cream sauce with herbs.", price: 13.49,
    imageUrl: "https://images.unsplash.com/photo-1556761223-4c4282c73f77?w=900&q=85", category: "Italian", cafeId: 1, cafeName: "Spice Garden Cafe",
    available: true, rating: 4.7, reviewCount: 73, createdAt: new Date().toISOString(),
  },
  {
    id: 21, name: "Loaded French Fries", description: "Crispy fries topped with cheese, herbs, and house seasoning.", price: 7.49,
    imageUrl: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=900&q=85", category: "Fast Food", cafeId: 2, cafeName: "Golden Wok",
    available: true, rating: 4.4, reviewCount: 62, createdAt: new Date().toISOString(),
  },
  {
    id: 22, name: "Crispy Veg Burger", description: "Crunchy vegetable patty with lettuce, tomato, and creamy sauce.", price: 9.49,
    imageUrl: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=900&q=85", category: "Fast Food", cafeId: 2, cafeName: "Golden Wok",
    available: true, rating: 4.5, reviewCount: 81, createdAt: new Date().toISOString(),
  },
  {
    id: 23, name: "Rasmalai", description: "Soft paneer dumplings soaked in chilled saffron milk.", price: 6.49,
    imageUrl: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=900&q=85", category: "Desserts", cafeId: 1, cafeName: "Spice Garden Cafe",
    available: true, rating: 4.8, reviewCount: 69, createdAt: new Date().toISOString(),
  },
  {
    id: 24, name: "Chocolate Brownie", description: "Warm fudgy chocolate brownie served with a rich cocoa finish.", price: 6.99,
    imageUrl: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=900&q=85", category: "Desserts", cafeId: 1, cafeName: "Spice Garden Cafe",
    available: true, rating: 4.7, reviewCount: 95, createdAt: new Date().toISOString(),
  },
  {
    id: 25, name: "Strawberry Milkshake", description: "Thick creamy milkshake blended with ripe strawberries.", price: 5.49,
    imageUrl: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=900&q=85", category: "Beverages", cafeId: 1, cafeName: "Spice Garden Cafe",
    available: true, rating: 4.6, reviewCount: 54, createdAt: new Date().toISOString(),
  },
  {
    id: 26, name: "Masala Chai", description: "Steaming Indian tea brewed with milk and aromatic spices.", price: 3.49,
    imageUrl: "https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?w=900&q=85", category: "Beverages", cafeId: 1, cafeName: "Spice Garden Cafe",
    available: true, rating: 4.8, reviewCount: 112, createdAt: new Date().toISOString(),
  },
  ...[
    ["Aloo Gobi", "Classic potato and cauliflower curry with warming spices.", 9.99, "Veg"],
    ["Vegetable Korma", "Mixed vegetables simmered in a creamy cashew gravy.", 11.49, "Veg"],
    ["Rajma Masala", "Red kidney beans slow-cooked in a rich tomato gravy.", 10.49, "Veg"],
    ["Malai Kofta", "Crispy paneer potato dumplings in silky royal gravy.", 12.99, "Veg"],
    ["Baingan Bharta", "Smoky roasted eggplant mashed with onion and tomato.", 9.49, "Veg"],
    ["Matar Paneer", "Paneer and green peas in a fragrant tomato sauce.", 11.99, "Veg"],
    ["Chicken Tikka", "Char-grilled yogurt-marinated chicken with Indian spices.", 14.49, "Non-Veg"],
    ["Lamb Kebab", "Juicy minced lamb skewers grilled with herbs and spices.", 16.49, "Non-Veg"],
    ["Fish Curry", "Tender fish cooked in a tangy coconut curry.", 15.99, "Non-Veg"],
    ["Chicken Korma", "Tender chicken in a mild cashew and cream sauce.", 15.49, "Non-Veg"],
    ["Prawn Masala", "Succulent prawns tossed in a spicy onion masala.", 17.49, "Non-Veg"],
    ["Chicken Seekh Kebab", "Minced chicken kebabs grilled with aromatic herbs.", 14.99, "Non-Veg"],
    ["Hot and Sour Soup", "Spicy tangy soup with vegetables and tofu.", 7.49, "Chinese"],
    ["Spring Rolls", "Crispy rolls filled with seasoned vegetables.", 7.99, "Chinese"],
    ["Manchow Soup", "Indo-Chinese soup topped with crunchy fried noodles.", 7.99, "Chinese"],
    ["Szechuan Chicken", "Tender chicken tossed in a fiery Szechuan sauce.", 14.99, "Chinese"],
    ["Honey Chilli Potato", "Crispy potatoes glazed with sweet chilli sauce.", 8.99, "Chinese"],
    ["Garlic Noodles", "Wok-tossed noodles with roasted garlic and spring onion.", 9.49, "Chinese"],
    ["Vegetable Spring Rice", "Fragrant fried rice with fresh seasonal vegetables.", 9.99, "Chinese"],
    ["Kung Pao Tofu", "Crispy tofu with peanuts, peppers, and chilli.", 11.49, "Chinese"],
    ["Four Cheese Pizza", "Wood-fired pizza with mozzarella, parmesan, cheddar, and blue cheese.", 15.99, "Italian"],
    ["Spaghetti Carbonara", "Spaghetti with creamy egg, parmesan, and cracked pepper.", 14.49, "Italian"],
    ["Lasagna", "Layered pasta with herbs, tomato sauce, and melted cheese.", 15.49, "Italian"],
    ["Mushroom Risotto", "Creamy arborio rice with wild mushrooms and parmesan.", 14.99, "Italian"],
    ["Pesto Pasta", "Pasta tossed with fresh basil pesto and parmesan.", 13.49, "Italian"],
    ["Garlic Bread", "Toasted bread with garlic butter and Italian herbs.", 6.49, "Italian"],
    ["Bruschetta", "Toasted bread topped with tomato, basil, and olive oil.", 7.49, "Italian"],
    ["Chicken Wings", "Crispy wings tossed in your choice of spicy sauce.", 12.99, "Fast Food"],
    ["Chicken Wrap", "Grilled chicken, salad, and sauce wrapped in soft flatbread.", 10.49, "Fast Food"],
    ["Hot Dog", "Juicy sausage in a toasted bun with mustard and relish.", 8.99, "Fast Food"],
    ["Cheese Nachos", "Crispy tortilla chips loaded with cheese and jalapenos.", 8.49, "Fast Food"],
    ["Fish and Chips", "Golden fried fish served with seasoned fries.", 13.99, "Fast Food"],
    ["Chicken Nuggets", "Golden bite-sized chicken nuggets with dipping sauce.", 9.49, "Fast Food"],
    ["Veggie Tacos", "Soft tortillas filled with vegetables, salsa, and cheese.", 9.99, "Fast Food"],
    ["Jalapeno Poppers", "Crispy stuffed jalapenos with creamy cheese filling.", 8.99, "Fast Food"],
    ["Kheer", "Creamy rice pudding flavored with cardamom and nuts.", 5.49, "Desserts"],
    ["Jalebi", "Crispy golden spirals soaked in fragrant sugar syrup.", 5.99, "Desserts"],
    ["Kulfi", "Traditional dense Indian ice cream with pistachio and saffron.", 5.99, "Desserts"],
    ["Gajar Halwa", "Warm carrot pudding cooked with milk, ghee, and nuts.", 6.49, "Desserts"],
    ["Rasgulla", "Soft cottage cheese balls soaked in light sugar syrup.", 5.49, "Desserts"],
    ["Mango Cheesecake", "Creamy cheesecake topped with fresh mango glaze.", 7.49, "Desserts"],
    ["Ice Cream Sundae", "Vanilla ice cream with chocolate sauce and toppings.", 6.99, "Desserts"],
    ["Cold Coffee", "Chilled blended coffee with milk and a creamy foam.", 5.49, "Beverages"],
    ["Fresh Lime Soda", "Refreshing lime soda served sweet or salted.", 3.99, "Beverages"],
    ["Watermelon Juice", "Freshly pressed watermelon juice served chilled.", 4.49, "Beverages"],
    ["Iced Tea", "Chilled black tea with lemon and a hint of sweetness.", 4.49, "Beverages"],
    ["Coconut Water", "Naturally refreshing tender coconut water.", 4.99, "Beverages"],
    ["Blueberry Smoothie", "Creamy yogurt smoothie blended with blueberries.", 6.49, "Beverages"],
    ["Virgin Mojito", "Sparkling mint and lime cooler with crushed ice.", 5.99, "Beverages"],
  ].map(([name, description, price, category], index) => ({
    id: 27 + index,
    name: name as string,
    description: description as string,
    price: price as number,
    imageUrl: NEW_DISH_IMAGES[name as string],
    category: category as string,
    cafeId: category === "Chinese" || category === "Fast Food" ? 2 : 1,
    cafeName: category === "Chinese" || category === "Fast Food" ? "Golden Wok" : "Spice Garden Cafe",
    available: true,
    rating: 4.5,
    reviewCount: 40 + index,
    createdAt: new Date().toISOString(),
  } as FoodItem)),
];

export function getFoodImage(food: Pick<FoodItem, "name" | "imageUrl">) {
  if (NEW_DISH_IMAGES[food.name]) return NEW_DISH_IMAGES[food.name];
  if (food.imageUrl?.includes("photo-1666190094762-7d1f5a7f7d1c")) {
    return DEMO_FOOD_ITEMS.find((item) => item.name === food.name)?.imageUrl ?? null;
  }
  if (food.imageUrl) return food.imageUrl;
  return DEMO_FOOD_ITEMS.find((item) => item.name === food.name)?.imageUrl ?? null;
}
