export const DEMO_IDEAS = [
  {
    id: 101,
    title: "Make restaurant-style naan without a tandoor",
    content: "Use a very hot cast-iron pan and brush the naan with butter as soon as it comes off the heat. The high heat creates beautiful bubbles and a soft center.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/04/Butter_Paneer_%2C_Butter_Naan_%2C_PK_017.jpg",
    authorId: 1,
    authorName: "Maya's Kitchen",
    authorRole: "user",
    likesCount: 128,
    reviewCount: 14,
    tags: ["bread", "indian", "quick"],
    createdAt: "2026-09-02T10:00:00.000Z",
  },
  {
    id: 102,
    title: "The secret to fluffy basmati rice",
    content: "Rinse the rice until the water runs clear, soak it for 20 minutes, then cook it with one part rice and one and a half parts water.",
    imageUrl: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/24/Cooked_basmati_rice_in_a_pot%2C_absorption_method%2C_fluffed.jpg/1280px-Cooked_basmati_rice_in_a_pot%2C_absorption_method%2C_fluffed.jpg",
    authorId: 2,
    authorName: "The Curry Club",
    authorRole: "cafe",
    likesCount: 96,
    reviewCount: 9,
    tags: ["rice", "tips"],
    createdAt: "2026-09-01T12:00:00.000Z",
  },
  {
    id: 103,
    title: "Crispy pakoras that stay crunchy",
    content: "Add a spoon of rice flour to your besan batter and keep the batter slightly thick. Fry in small batches so the oil temperature stays steady.",
    imageUrl: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1b/Pakoras_1.jpg/1280px-Pakoras_1.jpg",
    authorId: 3,
    authorName: "Spice Stories",
    authorRole: "user",
    likesCount: 84,
    reviewCount: 7,
    tags: ["snacks", "vegetarian"],
    createdAt: "2026-08-31T09:00:00.000Z",
  },
  {
    id: 104,
    title: "Five-minute garlic noodles",
    content: "Keep boiled noodles ready, then toss them with garlic, spring onions, soy sauce, sesame oil, and a pinch of chilli flakes in a very hot wok.",
    imageUrl: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7e/Hot_Dry_Noodles.jpg/1280px-Hot_Dry_Noodles.jpg",
    authorId: 4,
    authorName: "Wok This Way",
    authorRole: "user",
    likesCount: 73,
    reviewCount: 11,
    tags: ["noodles", "chinese", "fast"],
    createdAt: "2026-08-30T15:00:00.000Z",
  },
  {
    id: 105,
    title: "How to balance a curry",
    content: "If a curry tastes too spicy, add cream or coconut milk. If it tastes flat, try salt, lemon juice, or a little toasted spice powder before adding more chilli.",
    imageUrl: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3c/Chicken_makhani.jpg/1280px-Chicken_makhani.jpg",
    authorId: 5,
    authorName: "Chef Arjun",
    authorRole: "user",
    likesCount: 115,
    reviewCount: 18,
    tags: ["cooking-tips", "curry"],
    createdAt: "2026-08-29T11:00:00.000Z",
  },
  {
    id: 106,
    title: "A simple meal prep plan for busy weeks",
    content: "Prepare one grain, two roasted vegetables, and a versatile masala base on Sunday. Mix and match them with paneer, chicken, or beans throughout the week.",
    imageUrl: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e4/Meal_prep_container_%2844260855980%29.jpg/1280px-Meal_prep_container_%2844260855980%29.jpg",
    authorId: 6,
    authorName: "Daily Dabba",
    authorRole: "cafe",
    likesCount: 67,
    reviewCount: 6,
    tags: ["meal-prep", "healthy"],
    createdAt: "2026-08-28T08:00:00.000Z",
  },
];

export const DEMO_IDEA_REVIEWS = [
  { id: 1001, ideaId: 101, authorId: 8, authorName: "Riya", comment: "This worked perfectly on my cast-iron pan!", rating: 5, createdAt: "2026-09-02T14:00:00.000Z" },
  { id: 1002, ideaId: 101, authorId: 9, authorName: "Sam", comment: "Adding rice flour made a big difference.", rating: 5, createdAt: "2026-09-02T16:00:00.000Z" },
];

export function getDemoIdea(id: number) {
  return DEMO_IDEAS.find((idea) => idea.id === id);
}
